---
title: "Contribute Resources to ExperimentHub"
output:
  BiocStyle::html_document:
    toc: true
---
<!--
%% \VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Contribute Resources to ExperimentHub}
-->


# Overview

The `ExperimentHubData` package provides tools to add resources to
Bioconductor's `ExperimentHub`. This 'hub' houses curated data from courses,
publications or experiments.  These resources are not raw files (as can be the
case in `AnnotationHub`) but are instead `R` / `Bioconductor` objects such as
GRanges, SummarizedExperiment, data.frame etc.  Each resource has associated
metadata that can be searched through the `ExperimentHub` client interface.


# Adding resources

Resources are contributed to `ExperimentHub` in the form of a package.  The
package contains the resource metadata, man pages, vignette and any supporting
`R` functions the author wants to provide.  This is a similar design to the
existing `Bioconductor` experimental data packages except the data are
uploaded to AWS S3 buckets instead of stored in a data/ directory as part of
the pacakge.

New packages should be submitted to the `Bioconductor` tracker and will
have a full review. Contact packages@bioconductor.org for more information.

## Software package

When a resource is downloaded from `ExperimentHub` the associated software 
package is loaded so the man pages and vignettes are readily available.
Documentation plays an important role in these heavily curated resources. 
Clear man pages and a detailed vignette are essential to provide the necessary
background and analysis direction necessary to ensure the resources are
used appropriately.

Package organization:

* inst/scripts/
    - make-data.R

    Script demonstrating the steps involved in making the data object. Add
    a brief description and/or reference for steps not performed in `R`.

    - make-metadata.R

    Script to make metadata.csv. See ?`readMetadataFromCsv` for
    a description of expected fields and data types.  `readMetadataFromCsv()`
    can be used to validate metadata.csv before submitting the package.

* inst/extadata/
    - metadata.csv

    csv file with columns and data types as specified in 
    `ExperimentHubData::readMetadataFromCsv()`.

* vignettes/
    - One or more vignettes describing analysis workflows. 

* man/
    - package man page 
 
    The package man page serves as a landing point and should briefly describe
    all resources associated with the package. It is recommended (but not
    required) that each resource have a dedicated man page.

* R/
    - optional functions

## Data objects

Data are not included in the package but are uploaded to an AWS S3 bucket.
When a package is submitted for review the author is given access to an S3
bucket and is responsible for uploading the resource(s) using AWS CLI (command
line interface).

Data objects should be created with the script in inst/scripts/make-data.R.
Steps performed with third party software should be described in detail and 
appropriate references included.


# `ExperimentHub_docker`

The [ExperimentHub_docker](https://github.com/Bioconductor/ExperimentHub_docker)
offers an isolated test environment for inserting / extracting metadata records
in the `ExperimentHub` database. The README in the package explains how to
set up the Docker and inserting records is done with
`ExperimentHub::addResources()`.

In general this level of testing should not be necessary when submitting
a package with new resources. The best way to validate record metadata is to 
read inst/extdata/metadata.csv with `ExperimentHubData::readMetadataFromCsv()`.
If that is successful the metadata is ready to go.

# Updating resources / versioning

TBD
